##########################################
#              Bot Config                #
##########################################

BOT_CONFIG:
  PREFIX: "-"
  MONGO_URI: "mongodb://localhost:27017/discord"
  TOKEN: "TOKEN_DISCORD_BOT"
  GUILD_ID: "SERVER_ID"

##########################################
#            Activity Config             #
##########################################

ACTIVITY:
  ENABLED: true
  ACTIVITIES:
    - ["PLAYING", "Strider Development"]
  INTERVAL: "12h"

##########################################
#            Licenses Config             #
##########################################

LICENSES_CONFIG:
  WEB_PORT: 3000
  LOG_SYSTEM:
    ENABLED: true
    WEBHOOK_URL: "WEBHOOK_URL"
    WEBHOOK_IMAGE: "WEBHOOK_IMAGE"