##########################################
#              Bot Config                #
##########################################

BOT_CONFIG:
  MONGO_URI: "mongodb+srv://strider-dev:1FfUMui7btySjyUV@strider-dev.nbjci.mongodb.net/BlazeLicenseBot"
  TOKEN: "OTQwMzA5NzQ2ODIzNjEwNDA4.YgFhsQ.IN1cWN_xKqjTnti9mrPqpNXDqAI"
  GUILD_ID: "887479733732921376"

##########################################
#            Activity Config             #
##########################################

ACTIVITY:
  ENABLED: true
  ACTIVITIES:
    - ["PLAYING", "Strider Development"]
  INTERVAL: "12h"

##########################################
#            Licenses Config             #
##########################################

LICENSES_CONFIG:
  WEB_PORT: 3000
  LOG_SYSTEM:
    ENABLED: false
    WEBHOOK_URL: "WEBHOOK_URL"
    WEBHOOK_IMAGE: "WEBHOOK_IMAGE"