##########################################
#              Bot Config                #
##########################################

BOT_CONFIG:
  PREFIX: "-"
  MONGO_URI: "mongodb+srv://strider-dev:Jhoan2020@strider-dev.nbjci.mongodb.net/Blaze"
  TOKEN: "OTM3MTI4ODkwNzEzOTAzMTY0.YfXPSg.CLHYqdKpzASVxDOAQjZgMVq4Ntc"
  GUILD_ID: "887479733732921376"

##########################################
#            Activity Config             #
##########################################

ACTIVITY:
  ENABLED: true
  ACTIVITIES:
    - ["PLAYING", "Strider Development"]
  INTERVAL: "12h"

##########################################
#            Licenses Config             #
##########################################

LICENSES_CONFIG:
  WEB_PORT: 3000
  LOG_SYSTEM:
    ENABLED: true
    WEBHOOK_URL: "https://discord.com/api/webhooks/937774369185333271/5T_XHC4L3Ok64ub_vwux7P0ucnTKNc4bZ64-JG1pZS9hA4Rq_8lr8eyQvPZ67d4xh2Lm"
    WEBHOOK_IMAGE: "https://i.imgur.com/JuvRZOI.png"